apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDWjCCAkKgAwIBAgIVAO9rsRRP0krW8Nu5OD13+gzq8IMhMA0GCSqGSIb3DQEB
    CwUAMDQxMjAwBgNVBAMTKUVsYXN0aWMgQ2VydGlmaWNhdGUgVG9vbCBBdXRvZ2Vu
    ZXJhdGVkIENBMB4XDTI2MDYwNjAxMDMxMFoXDTI5MDYwNTAxMDMxMFowNDEyMDAG
    A1UEAxMpRWxhc3RpYyBDZXJ0aWZpY2F0ZSBUb29sIEF1dG9nZW5lcmF0ZWQgQ0Ew
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2hZMHKn21hdk2NTOBHqIs
    oALbac50IQu+uHPtz2o3KCN86DAQJyk1qAhhaTIf8cL51i/ybFvdlFmGyHSQfZ0l
    OxPG2kOrJCkw2GrnKyoTNs9yaz+nYGA0pFi2qmeZu2RCacx1lqHe0QZjSrseFZ0l
    hdSBpWM+G4+x6HIromZVjVG6bjgt28Mt84vysXdwTBzkUFv2bsR50YWigiQx01eh
    JvVTacEcomN6HpkDgFzjzlu2z/+GduOUgFaBUp4DQfMeBCzMYUS17oLwApbeRRK9
    zjJcOtP/3XI5fIrpjwykrZhxkcLaY3M/nIGvv091P01nnR9K/RUH3DLUv3Usts+5
    AgMBAAGjYzBhMB0GA1UdDgQWBBTdtckFE29f2LSqFE3bbL5QgEGMNDAfBgNVHSME
    GDAWgBTdtckFE29f2LSqFE3bbL5QgEGMNDAPBgNVHRMBAf8EBTADAQH/MA4GA1Ud
    DwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAQEAS5pWH99+KVjY984LEvgE7Uu+
    YRzR10G0ovbBMCxsKpU5M5qylIiGhoyKb/Bh5AYXAxCKOYvO1kQctMDNUsbM7gQe
    5dZgBrK4FW0FJ1UsVY//qohdnb/gC4TlNGh/sO5V0UISBjYI3LLrA6lO3nER7rET
    ytOxNePaH12VXGwXJw+mvUCxbq72gYwqNY2GiOGQS777FFTubRuTb8w29bAolc2J
    ThipWH03WhlN9wbZ8yPOIg62Y0siZyWerNChJpLBmOFv1RE03XvvQ0u6sioAJU2q
    koEoPQclXtjznENuZpz0smcIZGmcpe8qmaKWqpvAWTvV2FkTEWSNZnA3+K9OuQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: ca-configmap
