apiVersion: v1
data:
  tls.crt: /Users/bgebelek/Documents/Orchestration/Kubernetes/kubernetes-elastic-stack/ca/ca.crt
  tls.key: /Users/bgebelek/Documents/Orchestration/Kubernetes/kubernetes-elastic-stack/ca/ca.key
kind: Secret
metadata:
  name: ca-tls-secret
type: kubernetes.io/tls
