apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: es-http-route
spec:
  hostnames:
    - 'elasticsearch.elastic.com'
  parentRefs:
    - kind: Gateway
      name: elastic-gateway
  rules:
    - backendRefs:
        - name: es-clusterip-service
          port: 9200
