apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-node-discovery-service
  name: es-node-discovery-service
spec:
  clusterIP: None
  ports:
  - name: "9300"
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: es-statefulset
  type: ClusterIP
status:
  loadBalancer: {}
