apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-persistent-volume-e
spec:
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/es-persistent-volume-e
  storageClassName: es-persistent-volume
  capacity:
    storage: 5Gi
