apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: es-statefulset-hot
  name: es-statefulset-hot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: es-statefulset-hot
  serviceName: es-headless-service-hot-node-discovery
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: es-statefulset-hot
        part-of: es-statefulset
    spec:
      containers:
        - image: elasticsearch:9.3.2
          name: elasticsearch
          resources: 
            limits:
              memory: 2Gi
          volumeMounts:
            - name: es-config-volume
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: es-persistent-volume-claim
              mountPath: /usr/share/elasticsearch/data
            - name: es-certs-volume
              mountPath: /usr/share/elasticsearch/config/certs
          startupProbe:
            failureThreshold: 6
            periodSeconds: 10 
            tcpSocket:
              port: 9200
          readinessProbe:
            failureThreshold: 6
            exec:
              command:
                - '/bin/bash'
                - '-c'
                - 'curl --cacert /usr/share/elasticsearch/config/certs/ca.crt https://$HOSTNAME.es-headless-service-hot-node-discovery.default.svc.cluster.local:9200 | grep -q "missing authentication credentials"'
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: HEADLESS_SERVICE
              value: es-headless-service-hot-node-discovery
            - name: NODE_ROLE
              value: master,data_content,data_hot,ingest
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-auth-secret
                  key: password
      initContainers:
        - image: busybox:stable
          name: es-fix-data-dir-permissions
          command:
            - /bin/sh
          args:
            - '-c'	
            - 'chmod 757 /usr/share/elasticsearch/data && chown 1000:1000 /usr/share/elasticsearch/data'
          volumeMounts:
            - name: es-persistent-volume-claim
              mountPath: /usr/share/elasticsearch/data
          securityContext:
            privileged: true
      volumes:
        - name: es-config-volume
          configMap:
            name: es-configmap
        - name: es-certs-volume
          csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/duration: 8760h
              csi.cert-manager.io/renew-before: 360h
              csi.cert-manager.io/dns-names: ${POD_NAME}.es-headless-service-hot-node-discovery.default.svc.cluster.local,${POD_NAME}
              csi.cert-manager.io/ip-sans: 127.0.0.1
              csi.cert-manager.io/issuer-name: ca-issuer
  volumeClaimTemplates:
    - metadata:
        name: es-persistent-volume-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: es-persistent-volume
status: {}
