apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flt-deployment
  name: flt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flt-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: flt-deployment
    spec:
      containers:
        - image: docker.elastic.co/elastic-agent/elastic-agent:9.3.2
          name: elastic-agent
          resources: {}
          env:
            - name: FLEET_SERVER_ENABLE
              value: 'true'
            - name: FLEET_SERVER_POLICY_ID
              value: fleet-server-policy
            - name: FLEET_SERVER_CERT
              value: /mnt/certs/tls.crt
            - name: FLEET_SERVER_CERT_KEY
              value: /mnt/certs/tls.key
            - name: FLEET_SERVER_PORT
              value: '8220'
            - name: FLEET_URL
              value: https://flt-clusterip-service:8220
            - name: FLEET_CA
              value: /mnt/certs/ca.crt
            - name: FLEET_SERVER_ELASTICSEARCH_HOST
              value: https://es-clusterip-service:9200
            - name: FLEET_SERVER_ELASTICSEARCH_CA
              value: /mnt/certs/ca.crt
            - name: KIBANA_FLEET_HOST
              value: https://kb-clusterip-service:5601
            - name: KIBANA_CA
              value: /mnt/certs/ca.crt
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: kb-auth-secret
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: es-auth-secret
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: es-auth-secret
          volumeMounts:
            - name: flt-certs-volume
              mountPath: /mnt/certs
          startupProbe:
            failureThreshold: 6
            periodSeconds: 10
            tcpSocket:
              port: 8220
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /api/status
              port: 8220
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 10
      initContainers:
        - image: nicolaka/netshoot:latest
          name: flt-check-kb-running
          command:
            - /bin/sh
          args:
            - '-c'
            - 'until curl -sI --cacert /mnt/certs/ca.crt https://kb-clusterip-service:5601/login?next=%2F | grep -q "HTTP/2 200"; do sleep 30s; done'
          volumeMounts:
            - name: flt-certs-volume
              mountPath: /mnt/certs
      volumes:
        - name: flt-certs-volume
          secret:
            secretName: flt-tls-secret
status: {}
