apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flt-domain-certificate
spec:
  secretName: flt-domain-tls-secret
  duration: 8760h
  renewBefore: 360h
  isCA: false
  dnsNames:
    - fleet-server.elastic.com
  issuerRef:
    name: ca-issuer
