apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kb-deployment
  name: kb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kb-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: kb-deployment
    spec:
      containers:
      - image: kibana:9.3.2
        name: kibana
        resources: {}
        volumeMounts:
          - name: kb-volume
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
        startupProbe:
          failureThreshold: 6
          periodSeconds: 10
          tcpSocket:
            port: 5601
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /api/status
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
        - name: kb-volume
          configMap:
            name: kb-configmap
status: {}
