apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kb-deployment
  name: kb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kb-deployment
  template:
    metadata:
      labels:
        app: kb-deployment
    spec:
      containers:
        - image: kibana:9.3.2
          name: kibana
          resources: {}
          volumeMounts:
            - name: kb-config-volume
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
            - name: kb-certs-volume
              mountPath: /usr/share/kibana/config/certs
          startupProbe:
            failureThreshold: 6
            periodSeconds: 10
            tcpSocket:
              port: 5601
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /api/status
              port: 5601
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kb-auth-secret
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kb-auth-secret
                  key: password
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: kb-enc-key-secret
                  key: key
      initContainers:
        - image: nicolaka/netshoot:latest
          name: kb-check-auth
          command:
            - /bin/sh
          args:
            - '-c'
            - 'until curl -sIX GET --cacert /mnt/certs/ca.crt -H "Authorization: Basic $(echo -n $ELASTICSEARCH_USERNAME:$ELASTICSEARCH_PASSWORD | base64)" https://es-clusterip-service:9200/_security/_authenticate | grep -q "HTTP/1.1 200 OK"; do sleep 30s; done'
          volumeMounts:
            - name: kb-certs-volume
              mountPath: /mnt/certs
          env:
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kb-auth-secret
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kb-auth-secret
                  key: password
      volumes:
        - name: kb-config-volume
          configMap:
            name: kb-configmap
        - name: kb-certs-volume
          secret:
            secretName: kb-tls-secret
status: {}
