apiVersion: batch/v1
kind: Job
metadata:
  name: kb-service-account-setup
spec:
  template:
    metadata: {}
    spec:
      containers:
        - command:
            - /bin/sh
            - '-c'
            - 'until curl -s --cacert /mnt/ca/tls.crt https://es-clusterip-service:9200 | grep -q "missing authentication credentials"; do sleep 30s; done && until curl -sX POST --cacert /mnt/ca/tls.crt -u elastic:$ELASTIC_PASSWORD -H "Content-Type:application/json" https://es-clusterip-service:9200/_security/user/kibana_system/_password -d "{\"password\":\"$ELASTICSEARCH_PASSWORD\"}" | grep -q "^{}"; do sleep 10s; done'
          image: nicolaka/netshoot:latest
          name: kb-service-account-setup
          resources: {}
          volumeMounts:
            - name: jb-ca-certs-volume
              mountPath: /mnt/ca
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-auth-secret
                  key: password
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kb-auth-secret
                  key: password
      volumes:
        - name: jb-ca-certs-volume
          secret:
            secretName: ca-tls-secret
      restartPolicy: Never
status: {}
