apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kb-service-certificate
spec:
  secretName: kb-service-tls-secret
  duration: 8760h
  renewBefore: 360h
  isCA: false
  dnsNames:
    - kb-clusterip-service
  issuerRef:
    name: ca-issuer
