monitoring.ui.container.elasticsearch.enabled: true
server:
  host: "0.0.0.0"
  shutdownTimeout: "5s"
  ssl:
    enabled: true
    certificate: /usr/share/kibana/config/certs/instance/${HOSTNAME}/${HOSTNAME}.crt
    key: /usr/share/kibana/config/certs/instance/${HOSTNAME}/${HOSTNAME}.key
elasticsearch:
  hosts: 
    - https://es-clusterip-service:9200
  ssl:
    certificateAuthorities: /usr/share/kibana/config/certs/ca/tls.crt
xpack:
  fleet:
    packages:
      - name: fleet_server
        version: latest
    agentPolicies:
      - name: Default Agent Policy
        id: fleet-server-policy
        namespace: default
        package_policies:
          - name: fleet_server
            package:
              name: fleet_server
  encryptedSavedObjects:
    encryptionKey: ${ENCRYPTION_KEY}
