resources:
  - ca-issuer.yml
  - ca-tls-secret.yml
  - es-auth-secret.yml
  - es-clusterip-service.yml
  - es-headless-service-cold-node-discovery.yml
  - es-headless-service-hot-node-discovery.yml
  - es-persistent-volume-a.yml
  - es-persistent-volume-b.yml
  - es-persistent-volume-c.yml
  - es-persistent-volume-d.yml
  - es-statefulset-cold.yml
  - es-statefulset-hot.yml
  - flt-certificate.yml
  - flt-clusterip-service.yml
  - flt-deployment.yml
  - flt-nodeport-service.yml
  - kb-auth-secret.yml
  - kb-certificate.yml
  - kb-clusterip-service.yml
  - kb-enc-key-secret.yml
  - kb-deployment.yml
  - kb-service-account-setup.yml
  - kb-nodeport-service.yml

labels:
  - pairs:
      part-of: elastic-stack

configMapGenerator:
  - name: es-configmap
    files:
      - elasticsearch.yml
  - name: kb-configmap
    files:
      - kibana.yml
