resources:
  - es-statefulset-hot.yml
  - es-statefulset-warm.yml
  - es-statefulset-cold.yml
  - es-statefulset-frozen.yml
  - es-headless-service-hot-node-discovery.yml
  - es-headless-service-warm-node-discovery.yml
  - es-headless-service-cold-node-discovery.yml
  - es-headless-service-frozen-node-discovery.yml
  - es-service.yml
  - kb-deployment.yml
  - kb-service.yml
  - es-persistent-volume-a.yml
  - es-persistent-volume-b.yml

labels:
  - pairs:
      part-of: elastic-stack

configMapGenerator:
  - name: es-configmap
    files:
      - elasticsearch.yml
  - name: kb-configmap
    files:
      - kibana.yml
